language: python
python:
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
script: nosetests
after_success:
  - coveralls